# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-UrbanAirship
version:      0.01
version_from: lib/WebService/UrbanAirship.pm
installdirs:  site
requires:
    Crypt::SSLeay:                 0
    JSON::XS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
